---
# tasks file for dkusidlo.account-mgmt

### groups

- name: manage groups linux
  group:
    name: '{{ item.name }}'
    state: present
  with_items:
    '{{ user_groups }}'
  tags: configuration

- name: makedir /etc/ssh/conf.d/
  file:
    path: /etc/ssh/conf.d/
    state: directory
    mode: '0755'
  tags: ssh_configuration

- name: copy default sshd_config to /etc/ssh/conf.d/
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/conf.d/sshd_config
  tags: ssh_configuration

- name: manage groups sshd
  template:
    src: 'sshd_groups.j2'
    dest: '/etc/ssh/conf.d/sshd_config_{{ item.name }}'
  with_items:
    '{{ user_groups }}'
  tags: ssh_configuration

- name: assemble new sshd_config
  assemble:
    src: /etc/ssh/conf.d/
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
    backup: yes
    validate: '/usr/sbin/sshd -T -f %s'

### user ###
- name: manage user with password
  user:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    groups: '{{ item.groups }}'
    shell: '{{ item.shell }}'
    password: '{{ item.password }}'
  with_items:
    '{{ user }}'
  when:
    item.state == 'present' and item.password is defined
  tags: user_configuration

- name: manage user without password
  user:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    groups: '{{ item.groups }}'
    shell: '{{ item.shell }}'
    password: ''
  with_items:
    '{{ user }}'
  when:
    item.state == 'present' and item.password is not defined
  tags: user_configuration

- name: manage keys
  lineinfile:
    dest: '{{ key_location }}{{ item.name }}'
    line: '{{ item.key }}'
    insertafter: EOF
    create: yes
    backup: yes
    state: present
  with_items:
    '{{ user }}'
  ignore_errors: yes
  notify: restart sshd
  tags: ssh_keys
